### ISSUE TITLE
Add some license

### ISSUE THREAD

**Issue by fat-fellow** [JanFalkin/tantivy-jpc#213]
Hello. Thanks for open sourcing your work!
Could you please add some license to the repo?
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

> However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by JanFalkin** [comment]
Apache license 2.0 added
